'use client';

import { FormEvent, useState } from 'react';

const whatsappNumber = '5571992877538';

const waMessages = {
  default: 'Olá! Conheci a EcoSol Brasil Energia pelo site e gostaria de receber mais informações.',
  solar: 'Olá! Gostaria de solicitar uma análise para instalação de energia solar.',
  business: 'Olá! Gostaria de solicitar uma análise de energia solar para minha empresa.',
  condo: 'Olá! Gostaria de informações sobre infraestrutura e gerenciamento de carregadores para um condomínio.',
  ev: 'Olá! Gostaria de informações sobre instalação de carregador para veículo elétrico.',
};

function whatsappUrl(message: string) {
  return `https://wa.me/${whatsappNumber}?text=${encodeURIComponent(message)}`;
}

function openWhatsApp(message: string) {
  window.open(whatsappUrl(message), '_blank', 'noopener,noreferrer');
}

const solutions = [
  { eyebrow: '01 / GERAÇÃO', title: 'Energia solar residencial', text: 'Reduza sua conta produzindo eletricidade no próprio imóvel com um sistema dimensionado para o seu consumo.', action: 'Quero economizar', message: waMessages.solar, icon: '⌁', tone: 'green' },
  { eyebrow: '02 / PERFORMANCE', title: 'Energia solar empresarial', text: 'Transforme energia em redução de custos com projetos fotovoltaicos pensados para o perfil do seu negócio.', action: 'Solicitar análise', message: waMessages.business, icon: '↗', tone: 'blue' },
  { eyebrow: '03 / ESTRUTURA', title: 'Energia solar para condomínios', text: 'Soluções para áreas comuns e projetos desenvolvidos de acordo com a infraestrutura e demanda do condomínio.', action: 'Conhecer soluções', message: waMessages.condo, icon: '⌂', tone: 'orange' },
  { eyebrow: '04 / MOBILIDADE', title: 'Carregadores para veículos elétricos', text: 'Instalação de wallboxes e infraestrutura de recarga para residências, empresas e condomínios.', action: 'Conhecer carregadores', message: waMessages.ev, icon: '▣', tone: 'violet' },
];

const faqs = [
  ['Quanto posso economizar com energia solar?', 'A economia depende do consumo, da tarifa, da área disponível e do sistema dimensionado. A análise inicial mostra o potencial do seu imóvel sem promessas absolutas.'],
  ['Quanto custa instalar energia solar?', 'O investimento varia conforme a potência necessária, os equipamentos e as condições do local. Envie sua conta para receber uma estimativa personalizada.'],
  ['Como saber o tamanho do sistema que preciso?', 'A EcoSol avalia seu histórico de consumo, características do imóvel, orientação do telhado e espaço disponível antes de definir a potência.'],
  ['Energia solar funciona em dias nublados?', 'Sim. Os módulos continuam gerando energia com a luminosidade do dia, embora a produção varie conforme as condições climáticas.'],
  ['Quanto tempo dura um sistema fotovoltaico?', 'Os equipamentos são projetados para uma longa vida útil. A durabilidade exata depende do fabricante, da instalação e da manutenção.'],
  ['Posso instalar energia solar em condomínio?', 'Sim. É possível estudar soluções para áreas comuns e outras configurações, sempre considerando a infraestrutura e as regras do condomínio.'],
  ['Posso instalar um carregador de carro elétrico no meu apartamento?', 'Pode ser viável, mas é necessário analisar a vaga, o trajeto dos cabos, a medição e a capacidade elétrica da edificação.'],
  ['O condomínio precisa autorizar a instalação de um wallbox?', 'Em geral, intervenções em áreas comuns precisam seguir as regras internas. A EcoSol ajuda a organizar o estudo técnico para a decisão.'],
  ['É possível instalar vários carregadores no mesmo condomínio?', 'Sim. O projeto deve prever infraestrutura compartilhada, distribuição de potência e expansão gradual para preservar a segurança da instalação.'],
  ['O que é gerenciamento de carga para carregadores elétricos?', 'É o controle inteligente que distribui a potência disponível entre os carregadores, evitando ultrapassar os limites definidos para a instalação.'],
  ['A EcoSol Brasil faz análise técnica antes da instalação?', 'Sim. Cada proposta começa com uma análise da necessidade do cliente e da infraestrutura disponível.'],
];

function SectionIntro({ index, kicker, title, text, light = false }: { index: string; kicker: string; title: string; text: string; light?: boolean }) {
  return <div className={`section-intro ${light ? 'section-intro-light' : ''}`}><div className="section-index">{index}</div><div><p className="eyebrow">{kicker}</p><h2>{title}</h2></div><p className="section-intro-copy">{text}</p></div>;
}

function ArrowIcon() { return <span className="arrow-icon" aria-hidden="true">↗</span>; }

function LogoLockup({ dark = false }: { dark?: boolean }) {
  return <a className="logo-lockup" href="#inicio" aria-label="EcoSol Brasil Energia — início"><img src={dark ? "assets/ecosol-logo-horizontal-white.png" : "assets/ecosol-logo-horizontal.png"} alt="EcoSol Brasil" /></a>;
}

function WhatsAppButton({ message = waMessages.default, children, className = '' }: { message?: string; children: React.ReactNode; className?: string }) {
  return <button className={`button button-primary ${className}`} type="button" onClick={() => openWhatsApp(message)}>{children}<ArrowIcon /></button>;
}

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [bill, setBill] = useState('650');
  const [calculated, setCalculated] = useState(false);
  const [openFaq, setOpenFaq] = useState(0);

  const billValue = Number(bill.replace(',', '.')) || 0;
  const monthlySavings = billValue * 0.78;
  const annualSavings = monthlySavings * 12;
  const annualSavingsLabel = annualSavings.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL', maximumFractionDigits: 0 });
  const billLabel = billValue.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL', maximumFractionDigits: 0 });

  function handleContactSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const data = new FormData(event.currentTarget);
    const message = ['Olá! Gostaria de falar com a EcoSol Brasil Energia.', `Nome: ${data.get('nome') || ''}`, `WhatsApp: ${data.get('whatsapp') || ''}`, `E-mail: ${data.get('email') || ''}`, `Cidade: ${data.get('cidade') || ''}`, `Tipo de projeto: ${data.get('projeto') || ''}`, `Mensagem: ${data.get('mensagem') || ''}`].join('\n');
    openWhatsApp(message);
  }

  return (
    <main>
      <div className="topline"><span>ENERGIA INTELIGENTE PARA UM FUTURO MAIS SUSTENTÁVEL</span><span className="topline-location">BRASIL</span></div>

      <header className="site-header"><div className="container header-inner"><LogoLockup /><button className="menu-toggle" type="button" aria-label={menuOpen ? 'Fechar menu' : 'Abrir menu'} aria-expanded={menuOpen} onClick={() => setMenuOpen((open) => !open)}><span /><span /></button><nav className={menuOpen ? 'site-nav nav-open' : 'site-nav'} aria-label="Navegação principal"><a href="#inicio" onClick={() => setMenuOpen(false)}>Início</a><a href="#solucoes" onClick={() => setMenuOpen(false)}>Energia Solar</a><a href="#mobilidade" onClick={() => setMenuOpen(false)}>Carregadores</a><a href="#condominios" onClick={() => setMenuOpen(false)}>Condomínios</a><a href="#como-funciona" onClick={() => setMenuOpen(false)}>Como funciona</a><a href="#projetos" onClick={() => setMenuOpen(false)}>Projetos</a><a href="#sobre" onClick={() => setMenuOpen(false)}>Sobre nós</a><a href="#contato" onClick={() => setMenuOpen(false)}>Contato</a></nav><WhatsAppButton message={waMessages.default} className="header-cta">Solicitar orçamento</WhatsAppButton></div></header>

      <section id="inicio" className="hero-section"><div className="hero-grid" aria-hidden="true" /><div className="hero-glow hero-glow-one" aria-hidden="true" /><div className="hero-glow hero-glow-two" aria-hidden="true" /><div className="container hero-content"><div className="hero-copy"><p className="eyebrow eyebrow-bright">ECOSOL BRASIL ENERGIA <span>— 01</span></p><h1>Economize energia.<br /><em>Gere a sua.</em></h1><p className="hero-subtitle">Soluções completas em energia solar e mobilidade elétrica para residências, empresas e condomínios.</p><div className="hero-actions"><WhatsAppButton message={waMessages.default}>Solicitar orçamento</WhatsAppButton><a className="button button-ghost" href="#solucoes">Conhecer soluções <ArrowIcon /></a></div><div className="hero-proof-row"><span><b className="proof-dot proof-dot-green" /> Energia limpa</span><span><b className="proof-dot proof-dot-blue" /> Projeto personalizado</span><span><b className="proof-dot proof-dot-orange" /> Instalação especializada</span><span><b className="proof-dot proof-dot-white" /> Suporte técnico</span></div></div><div className="hero-visual" aria-label="Composição visual de energia solar e mobilidade elétrica"><div className="visual-orbit orbit-one" /><div className="visual-orbit orbit-two" /><div className="solar-panel-art"><div className="panel-lines" /><div className="panel-highlight" /></div><div className="hero-house-card"><div className="house-line house-roof" /><div className="house-line house-body" /><div className="house-window" /><span>CASA + ENERGIA</span></div><div className="hero-system-card"><span className="status-dot" /><span>GERAÇÃO AGORA</span><strong>4,82 <small>kW</small></strong><div className="mini-bars"><i /><i /><i /><i /><i /><i /></div></div><div className="hero-visual-label">01 <span>sol + tecnologia</span></div></div></div><div className="container hero-bottom-note"><span>DO SOL PARA O SEU FUTURO</span><span className="scroll-note"><i /> role para explorar</span></div></section>

      <section className="partner-strip"><div className="container partner-inner"><p>Uma escolha segura começa com parceiros confiáveis.</p><div className="partner-logos"><span>PARCEIRO CREDENCIADO</span><img src="assets/intelbras-partner.jpg" alt="Parceiro credenciado Intelbras" /></div><div className="partner-divider" /><div className="partner-note"><b>BR</b><span>Atendemos todo o Brasil</span></div></div></section>

      <section id="solucoes" className="section section-solutions"><div className="container"><SectionIntro index="02" kicker="SOLUÇÕES ECOSOL" title="Energia para cada necessidade." text="Do primeiro raio de sol ao gerenciamento inteligente de carga: projetamos a solução que faz sentido para o seu momento." /><div className="solutions-grid">{solutions.map((solution) => <article className={`solution-card tone-${solution.tone}`} key={solution.title}><div className="solution-card-top"><span className="solution-eyebrow">{solution.eyebrow}</span><span className="solution-icon">{solution.icon}</span></div><h3>{solution.title}</h3><p>{solution.text}</p><button type="button" className="text-button" onClick={() => openWhatsApp(solution.message)}>{solution.action} <ArrowIcon /></button></article>)}</div></div></section>

      <section id="economia" className="section section-economy"><div className="container economy-layout"><div className="economy-copy"><div className="section-index section-index-light">03</div><p className="eyebrow eyebrow-bright">ECONOMIA QUE SE PLANEJA</p><h2>Transforme sua conta de energia <em>em investimento.</em></h2><p>Com um sistema fotovoltaico, parte significativa da energia consumida pelo imóvel pode ser produzida pelo próprio sistema solar.</p><div className="benefit-list"><span><b>↘</b> redução da conta de energia</span><span><b>↗</b> proteção contra aumentos tarifários</span><span><b>⌂</b> valorização do imóvel</span><span><b>∞</b> longa vida útil dos equipamentos</span></div><a className="button button-outline-light" href="#simulador">Descubra quanto pode economizar <ArrowIcon /></a></div><div className="economy-visual"><div className="economy-rings" aria-hidden="true"><i /><i /><i /></div><div className="economy-center"><span>ENERGIA<br />GERADA</span><strong>78%</strong><small>potencial médio ilustrativo</small></div><div className="economy-tag economy-tag-top"><span>01</span> menos dependência</div><div className="economy-tag economy-tag-bottom"><span>02</span> mais previsibilidade</div></div></div></section>

      <section id="simulador" className="section section-simulator"><div className="container simulator-layout"><div className="simulator-intro"><p className="eyebrow">SIMULADOR INICIAL <span>— sem compromisso</span></p><h2>Quanto você paga <em>de energia?</em></h2><p>Faça uma estimativa rápida do potencial de economia da sua conta mensal. Depois, nossa equipe pode analisar os detalhes do seu imóvel.</p><div className="simulator-tip"><span>i</span><p>O resultado é apenas uma estimativa inicial. O dimensionamento definitivo depende de análise técnica.</p></div></div><div className="calculator-card"><label htmlFor="energy-bill">Valor médio da conta mensal</label><div className="input-money"><span>R$</span><input id="energy-bill" inputMode="decimal" value={bill} onChange={(event) => { setBill(event.target.value); setCalculated(false); }} aria-describedby="bill-help" /></div><p id="bill-help" className="input-help">Use o valor aproximado da sua última conta.</p><button className="button button-dark" type="button" onClick={() => setCalculated(true)}>Calcular estimativa <ArrowIcon /></button><div className={`estimate-result ${calculated ? 'estimate-visible' : ''}`} aria-live="polite"><div className="estimate-head"><span>ECONOMIA POTENCIAL ANUAL</span><strong>{annualSavingsLabel}</strong></div><div className="estimate-bar"><i style={{ width: `${Math.min(92, Math.max(8, billValue ? 78 : 8))}%` }} /></div><div className="estimate-meta"><span>Conta atual: {billLabel}/mês</span><span>estimativa ilustrativa</span></div><button className="estimate-cta" type="button" onClick={() => openWhatsApp(`Olá! Gostaria de receber uma análise para instalação de energia solar. Minha conta média de energia é de aproximadamente ${billLabel} por mês.`)}>Enviar minha conta pelo WhatsApp <ArrowIcon /></button></div></div></div></section>

      <section id="mobilidade" className="section section-mobility"><div className="container mobility-layout"><div className="mobility-visual mobility-photo"><img src="assets/carregadores-hero.png" alt="Carro elétrico sendo carregado em um wallbox Intelbras" /></div><div className="mobility-copy"><div className="section-index">04</div><p className="eyebrow">MOBILIDADE ELÉTRICA</p><h2>Sua garagem também está entrando <em>na era elétrica.</em></h2><p>A EcoSol Brasil oferece soluções de carregamento para veículos elétricos em residências, empresas e condomínios — com técnica, segurança e espaço para crescer.</p><div className="mobility-list"><span>Wallbox residencial</span><span>Carregadores empresariais</span><span>Infraestrutura para estacionamentos</span><span>Gerenciamento de carga</span><span>Expansão futura</span></div><WhatsAppButton message={waMessages.ev}>Quero instalar um carregador</WhatsAppButton></div></div></section>

      <section id="condominios" className="section section-condos"><div className="container"><SectionIntro index="05" kicker="INFRAESTRUTURA INTELIGENTE" title="Carregamento inteligente para condomínios." text="Quando vários moradores carregam ao mesmo tempo, a infraestrutura precisa acompanhar. O projeto certo organiza a energia hoje e prepara o condomínio para o futuro." /><div className="condo-content"><div className="condo-copy"><p>Antes de instalar diversos carregadores, analisamos a capacidade elétrica disponível e desenhamos uma infraestrutura compartilhada, segura e expansível.</p><div className="condo-points"><span>análise da capacidade disponível</span><span>controle de potência</span><span>expansão gradual</span><span>segurança elétrica</span><span>organização da infraestrutura</span><span>gerenciamento de demanda</span></div><WhatsAppButton message={waMessages.condo}>Solicitar estudo para meu condomínio</WhatsAppButton></div><div className="load-diagram" aria-label="Diagrama de gerenciamento de carga para condomínio"><div className="diagram-node diagram-source"><small>REDE DO</small><strong>CONDOMÍNIO</strong><span className="node-mark">⌁</span></div><div className="diagram-line"><i /></div><div className="diagram-node diagram-controller"><small>CONTROLE</small><strong>CONTROLADOR<br />DE CARGA</strong><span className="node-mark">◌</span></div><div className="diagram-branch"><i /><i /><i /></div><div className="diagram-chargers"><div><span>01</span> carregador</div><div><span>02</span> carregador</div><div><span>03</span> carregador</div></div><div className="diagram-vehicles"><span>EV</span><span>EV</span><span>EV</span></div></div></div></div></section>

      <section id="como-funciona" className="section section-process"><div className="container"><SectionIntro index="06" kicker="DO PRIMEIRO CONTATO À GERAÇÃO" title="Como funciona um projeto solar." text="Um caminho claro, com acompanhamento próximo em cada decisão." /><div className="process-timeline">{[['01', 'Análise', 'Entendemos o consumo de energia e as características do imóvel.'], ['02', 'Dimensionamento', 'Calculamos a potência necessária e definimos a solução adequada.'], ['03', 'Projeto', 'Desenvolvemos o projeto técnico da instalação.'], ['04', 'Instalação', 'Nossa equipe realiza a instalação dos equipamentos.'], ['05', 'Geração', 'O sistema começa a produzir energia para o imóvel.']].map(([number, title, text], index) => <article className={`process-step ${index === 4 ? 'process-step-final' : ''}`} key={number}><div className="process-number">{number}</div><div className="process-dot" /><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>

      <section id="projetos" className="section section-projects"><div className="container"><SectionIntro index="07" kicker="PORTFÓLIO EM CONSTRUÇÃO" title="Projetos EcoSol Brasil." text="Cada projeto nasce de uma necessidade diferente. Em breve, esta seleção vai mostrar mais histórias de energia, eficiência e mobilidade elétrica." /><div className="project-grid">{[['Residencial', 'Energia que acompanha a rotina', '01'], ['Comercial', 'Eficiência para o seu negócio', '02'], ['Condomínio', 'Infraestrutura pronta para crescer', '03'], ['Mobilidade elétrica', 'Recarga onde a vida acontece', '04']].map(([category, title, number], index) => <article className={`project-card project-card-${index + 1}`} key={category}><div className="project-art"><span>{number}</span><i /></div><div className="project-info"><small>{category}</small><h3>{title}</h3><p>Estrutura reservada para foto, cidade, potência instalada e descrição do projeto.</p></div></article>)}</div><p className="project-footnote"><span>+</span> Novos projetos serão adicionados aqui.</p></div></section>

      <section className="section section-differentials"><div className="container"><SectionIntro index="08" kicker="O JEITO ECOSOL DE FAZER" title="Por que escolher a EcoSol Brasil?" text="A melhor solução não é a maior. É a que combina com sua realidade, seu espaço e seus próximos passos." /><div className="differentials-grid">{[['01', 'Projeto personalizado', 'Cada instalação é dimensionada de acordo com a realidade do cliente.'], ['02', 'Tecnologia', 'Equipamentos e soluções modernas para geração e gerenciamento de energia.'], ['03', 'Segurança', 'Projetos desenvolvidos considerando normas técnicas e segurança elétrica.'], ['04', 'Atendimento próximo', 'Acompanhamento desde a análise inicial até a instalação.'], ['05', 'Visão de futuro', 'Geração solar e mobilidade elétrica em uma mesma visão de energia.']].map(([number, title, text]) => <article className="differential" key={title}><span>{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>

      <section id="sobre" className="section section-about"><div className="container about-layout"><div className="about-mark"><img src="assets/ecosol-logo.png" alt="EcoSol Brasil" /><span>ENERGIA · TECNOLOGIA · EFICIÊNCIA</span></div><div className="about-copy"><p className="eyebrow">SOBRE A ECOSOL BRASIL</p><h2>Energia, tecnologia <em>e eficiência.</em></h2><p>A EcoSol Brasil Energia desenvolve soluções para clientes que desejam consumir energia de forma mais eficiente, econômica e sustentável.</p><p>Trabalhamos com projetos de energia solar fotovoltaica e soluções de carregamento para veículos elétricos, atendendo residências, empresas e condomínios.</p><p>Cada projeto começa com uma análise da necessidade do cliente e da infraestrutura disponível, permitindo desenvolver uma solução adequada para cada cenário.</p><a className="text-button" href="#contato">Conheça a EcoSol Brasil <ArrowIcon /></a></div></div></section>

      <section className="section section-faq"><div className="container faq-layout"><div className="faq-intro"><p className="eyebrow">DÚVIDAS FREQUENTES</p><h2>Clareza para <em>decidir melhor.</em></h2><p>Se sua pergunta não estiver aqui, fale com nossa equipe. A análise começa com uma conversa.</p><WhatsAppButton message={waMessages.default}>Falar com um especialista</WhatsAppButton></div><div className="faq-list">{faqs.map(([question, answer], index) => <div className={`faq-item ${openFaq === index ? 'faq-open' : ''}`} key={question}><button type="button" onClick={() => setOpenFaq(openFaq === index ? -1 : index)} aria-expanded={openFaq === index}><span>{question}</span><b>{openFaq === index ? '−' : '+'}</b></button><div className="faq-answer"><p>{answer}</p></div></div>)}</div></div></section>

      <section className="section section-final-cta"><div className="cta-grid" aria-hidden="true" /><div className="container final-cta-inner"><p className="eyebrow eyebrow-bright">PRÓXIMO PASSO <span>— simples assim</span></p><h2>Quer reduzir seus custos <em>com energia?</em></h2><p>Envie sua conta de energia e converse com nossa equipe. Podemos realizar uma análise inicial da sua necessidade.</p><div className="hero-actions"><WhatsAppButton message={waMessages.default}>Falar com a EcoSol Brasil</WhatsAppButton><button className="button button-ghost" type="button" onClick={() => openWhatsApp('Olá! Gostaria de enviar minha conta de energia para uma análise da EcoSol Brasil.')}>Enviar minha conta de energia <ArrowIcon /></button></div></div></section>

      <section id="contato" className="section section-contact"><div className="container contact-layout"><div className="contact-copy"><p className="eyebrow">VAMOS CONVERSAR</p><h2>Seu projeto começa <em>aqui.</em></h2><p>Conte um pouco sobre o que você precisa. Nossa equipe retorna pelo WhatsApp para entender o cenário e indicar o próximo passo.</p><div className="contact-details"><a href="https://wa.me/5571992877538" target="_blank" rel="noreferrer"><span>WhatsApp</span><strong>(71) 99287-7538</strong></a><a href="https://instagram.com/ecosolbrasilenergia" target="_blank" rel="noreferrer"><span>Instagram</span><strong>@ecosolbrasilenergia</strong></a><a href="https://www.ecosolbrasilenergia.com.br" target="_blank" rel="noreferrer"><span>Site</span><strong>ecosolbrasilenergia.com.br</strong></a></div></div><form className="contact-form" onSubmit={handleContactSubmit}><div className="form-row"><label>Nome<input required name="nome" type="text" placeholder="Como podemos chamar você?" /></label><label>WhatsApp<input required name="whatsapp" type="tel" placeholder="(00) 00000-0000" /></label></div><div className="form-row"><label>E-mail<input name="email" type="email" placeholder="seu@email.com" /></label><label>Cidade<input name="cidade" type="text" placeholder="Ex.: sua cidade" /></label></div><label>Tipo de projeto<select required name="projeto" defaultValue=""><option value="" disabled>Selecione uma opção</option><option>Energia Solar Residencial</option><option>Energia Solar Comercial</option><option>Condomínio</option><option>Carregador para Veículo Elétrico</option><option>Outro</option></select></label><label>Mensagem<textarea name="mensagem" rows={4} placeholder="Fale brevemente sobre o seu projeto (opcional)" /></label><button className="button button-dark form-submit" type="submit">Solicitar contato <ArrowIcon /></button><p className="form-privacy">Ao enviar, você será direcionado para o WhatsApp da EcoSol Brasil.</p></form></div></section>

      <footer className="site-footer"><div className="container footer-top"><LogoLockup dark /><p>Energia inteligente para um futuro sustentável.</p><div className="footer-social"><a href="https://instagram.com/ecosolbrasilenergia" target="_blank" rel="noreferrer" aria-label="Instagram EcoSol Brasil">ig</a><a href="https://wa.me/5571992877538" target="_blank" rel="noreferrer" aria-label="WhatsApp EcoSol Brasil">wa</a></div></div><div className="container footer-bottom"><nav aria-label="Links do rodapé"><a href="#solucoes">Energia Solar</a><a href="#mobilidade">Carregadores Elétricos</a><a href="#condominios">Condomínios</a><a href="#projetos">Projetos</a><a href="#sobre">Sobre nós</a><a href="#contato">Contato</a><a href="#contato">Política de Privacidade</a></nav><span>© {new Date().getFullYear()} EcoSol Brasil Energia</span></div></footer>

      <button className="floating-whatsapp" type="button" onClick={() => openWhatsApp(waMessages.default)} aria-label="Falar com a EcoSol Brasil pelo WhatsApp"><span>wa</span><i>Fale com a gente</i></button>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ '@context': 'https://schema.org', '@type': 'LocalBusiness', name: 'EcoSol Brasil Energia', url: 'https://www.ecosolbrasilenergia.com.br', telephone: '+55 71 99287-7538', areaServed: 'Brasil', sameAs: ['https://instagram.com/ecosolbrasilenergia'], description: 'Soluções em energia solar fotovoltaica, carregadores para veículos elétricos e gerenciamento de carga em todo o Brasil.' }) }} />
    </main>
  );
}
